ProjekTugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_home_status.urls as app_home_status
import app_profile_page.urls as app_profile_page
import app_add_friend.urls as app_add_friend
import app_statistic_page.urls as app_statistic_page
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home-status/', include(app_home_status, namespace='home-status')),
    url(r'^profile-page/', include(app_profile_page,namespace='profile-page')),
    url(r'^add-friend/', include(app_add_friend, namespace='add-friend')),
    url(r'^my-stats/', include(app_statistic_page,namespace='my-stats')),
    url(r'^$', RedirectView.as_view(url='home-status/', permanent='true'), name='index'),
]

app_add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
]

app_home_status/urls.py
from django.conf.urls import url
from .views import index, add_status, comment, add_comment

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^comment/(?P<id>\w{0,50})/$', comment, name='comment'),
    url(r'^add_comment/(?P<id>\w{0,50})/$', add_comment, name='add_comment'),
]

app_profile_page/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_statistic_page/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_add_friend/models.py
from django.db import models

class Message(models.Model):
        name = models.CharField(max_length=27)
        url = models.CharField(max_length=200)
        created_date = models.DateTimeField(auto_now_add=True)

app_home_status/models.py
from django.db import models

class Status(models.Model):
    status = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

class Comments(models.Model):
    post = models.ForeignKey(Status, on_delete=models.CASCADE, null = True)
    nama = models.TextField()
    comment = models.TextField()
    comments_created_date = models.DateTimeField(auto_now_add=True)

app_profile_page/models.py
from django.db import models

class Profile(models.Model):

    name = models.CharField(max_length=64)
    email = models.EmailField()
    birth_date = models.DateField()
    expertise =  models.TextField()     #comma-separated
    gender = models.CharField(max_length=8)
    description = models.CharField(max_length=128)
    picture_url = models.URLField()

app_statistic_page/models.py
from django.db import models

# Create your models here.

app_add_friend/forms.py
from django import forms

class Message_Form(forms.Form):
    error_messages = {
        'required': 'Field ini wajib diisi',
		'invalid': 'Mohon diisi dengan link',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=True, max_length=27,widget=forms.TextInput(attrs=attrs))
    url = forms.CharField(label='Heroku URL',widget=forms.URLInput(attrs=attrs), required=True)

app_home_status/forms.py
from django import forms

class Status_Form(forms.Form):
    status_attrs = {
        'type': 'text',
        'rows': 4,
        'class' : 'form-control',
        'placeholder':"What's happening?",
        'style' : 'resize:none'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

class Comment_Form(forms.Form):
    comment_attrs = {
        'type': 'text',
        'rows': 4,
        'class' : 'form-control',
        'placeholder':"Ketik your comment here..",
        'style' : 'resize:none'
    }

    nama_attrs = {
        'type': 'text',
        'rows': 1,
        'class' : 'form-control',
        'placeholder':"Ketik nama lu..",
        'style' : 'resize:none'
    }
    
    nama = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=nama_attrs))
    comment = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=comment_attrs))
    

ProjekTugas1/views.py
from django.shortcuts import render, HttpResponsePermanentRedirect

#TODO Implement
#Create a content paragraph for your landing page:

def index(request):
    return HttpResponsePermanentRedirect('/home-status')

app_add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message

response = {'author': "Reza Akbar Shahputra"}
def index(request):
	html = 'add_friend/add_friend.html'
	response['message_form'] = Message_Form
	data = Message.objects.all()
	response['data'] = data
	return render(request, html, response)

def add_friend(request):
	form = Message_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['name'] = request.POST['name']
		response['url'] = request.POST['url']
		data = Message(name=response['name'], url=response['url'])
		data.save()
		return HttpResponseRedirect('/add-friend/')
	else:
		return HttpResponseRedirect('/add-friend/')

app_home_status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Status, Comments
from .forms import Status_Form, Comment_Form
from app_profile_page.active_profile import get_active_profile

# Create your views here.
response = {}

def index(request):
    profile = get_active_profile()
    status = Status.objects.order_by('-created_date')
    comments = Comments.objects.all()
    response['nama'] = profile.name
    response['picture'] = profile.picture_url
    response['status'] = status
    response['status_form'] = Status_Form
    response['comments'] = comments
    html = 'home_status.html'
    return render(request, html, response)

def add_status(request):
    response['status'] = request.POST['status']
    status = Status(status=response['status'])
    status.save()
    return HttpResponseRedirect('/home-status')

def comment(request,id):
    status = Status.objects.get(id=id)
    response['status'] = status
    response['comment_form'] = Comment_Form
    html = 'comment_status.html'
    return render(request, html, response)

def add_comment(request,id):
    response['adding_comment'] = request.POST['comment']
    response['nama'] = request.POST['nama']
    response['status'] = Status.objects.get(id=id)
    comment = Comments(comment = response['adding_comment'], nama = response['nama'],  post = response['status'])
    comment.save()
    return HttpResponseRedirect('/home-status')

app_profile_page/views.py
from django.shortcuts import render
from datetime import datetime, date
from .active_profile import get_active_profile


# Create your views here.
exp = ['Marketing', 'Collector', 'Programmer']
def index(request):

    profile = get_active_profile()
    response = {'name': profile.name,'description': profile.description, 'gender': profile.gender,
                'email': profile.email, 'birth': profile.birth_date, 'expertise': exp,
                'picture': profile.picture_url}
    return render(request, 'profile_page.html', response)

app_statistic_page/views.py
from django.shortcuts import render
from app_home_status.models import Status
from app_home_status.forms import Status_Form
from app_add_friend.models import Message
# Create your views here.

response = {}
def index(request):
    status = Status.objects.order_by('-created_date')
    if len(status) != 0:
        statusAkhir = Status.objects.order_by('-created_date')[0]
        response['statusAkhir'] = statusAkhir
    else:
        response['statusAkhir'] = 'Tidak ada status'

    response['number_of_feed'] = Status.objects.all().count()
    response['number_of_friend'] = Message.objects.all().count()
    html = 'statistic_page.html'
    return render(request, html, response)

app_add_friend/templates/add_friend/add_friend.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}


<br>
<section name="form" class="container">
		<h3 style="color:black;">Add Friend</h3>
		<form id="form" method="POST" action="{% url 'add-friend:add_friend' %}">
			{% csrf_token %}
			{{ message_form }}
			<br>
			<button type="submit" class="btn btn-default">Add</button>
		</form>
</section>
<br>
{%include "add_friend/table.html"%}
{% endblock %}

app_add_friend/templates/add_friend/table.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}

<div class = "container">
	<h3>
		List Friend
	</h3>
	
	<div class="table-responsive">
		<table class="table text-center table-hover">
		<thead>
			<th style = "text-align:center">Name</th>
			<th style = "text-align:center">Heroku Link</th>
			<th style = "text-align:center">Addition Date</th>
		</thead>
		<tbody>
			{% for i in data %}
			<tr class="info">
				<td> {{i.name}} </td>
				<td><a href= "{{i.url}}" style="color: black;">{{i.url}}</a> </td>
				<td> Added {{i.created_date | date:"d M Y H:i:s"}} </td>
			</tr>             
			{% endfor %}
		</tbody>
		</table>
	</div>
</div>
{% endblock %}

app_home_status/templates/comment_status.html
{% extends "base.html" %}

{% block content %}

<div class = "container">
    <section name="update_status" id="update_status">
        <form id="form" method="POST" action="{% url 'home-status:add_comment' status.id %}">
            <h3>Update Status</h3>
            {% csrf_token %}
            {{ comment_form }}
            <br>
            <input class="btn btn-default btn-primary" type="submit" value="Post" style="float: right;">
            <br>
        </form>
        <br>
    </section>
</div>
{% endblock %}

app_home_status/templates/home_status.html
{% extends "base.html" %}

{% block content %}

<style>
    #flex-luar{
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      justify-content: flex-start;
      align-items: flex-start;
      align-content: flex-start;
    }
  #flex-item-luar{
      padding: 0 15px;
      flex-grow: 0;
      flex-shrink: 0;
      flex-basis: 100%;
      background-color: rgba(164, 164, 164, 0.3);
      border-radius: 10px;
      margin-bottom:25px;
      width: 100%;
    }
    #flex-dalam{
        display: flex;
        flex-direction: row;
    }
    #container-status{
        width:69%
    }

    @media only screen and (max-width: 768px){
        .flex-item-status{
            width: 85%;
        }
        #container-status{
            width:90%;
        }
    }

    @media only screen and (max-width: 425px){
        .adding-comment-link{
            transform: translateX(-5vw);
        }
    }
  </style>

<!-- bikin konten buat tiap fitur di sini yak-->
<div class = "container" id="container-status">
    <section name="update_status" id="update_status">
        <form id="form" method="POST" action="{% url 'home-status:add_status' %}">
            <h3>Update Status</h3>
            {% csrf_token %}
            {{ status_form }}
            <br>
            <input id="submit" type="submit" class="btn btn-default btn-primary" value="Post" style="float: right;">
            <br>
        </form>
        <br>
    </section>
    <section name ="status_history" id = "status_history">
        <br>       
        <div class="flex" id = "flex-luar">
            {% for i in status %}
            <div class="flex-item" id="flex-item-luar">
                <div class="flex" id = 'flex-dalam'>
                    <div class="flex-item">
                        <div id="foto" style="font-weight: bold; margin-top:10px;">
                            <img src="https://orig00.deviantart.net/08ce/f/2008/235/9/2/hepzibah_smith_by_jlestrange.jpg" alt="gambar" width = "55px" height = "55px" style="border-radius:50%">
                        </div>
                    </div>
                    <div class="flex-item" style="padding-left:15px;margin-top:10px;width:87%">
                        <b> {{ nama }}</b>
                        <p class = "flex-item-status" style="font-size: 15px;word-wrap:break-word;">
                                {{ i.status | linebreaksbr }}
                        </p>
                        <div id="created_date" style="font-size:80%; font-style:italic;margin-bottom:5px; color: white"> {{ i.created_date | date:"d M Y H:i:s" }}</div>
                        <div class="adding-comment-link" align="right">
                            <a href="{% url 'home-status:comment' i.id %}" style="color: white;font-size:85%;">
                                Add Comment
                            </a>
                        </div>
                    </div>
                </div>
                {% for j in comments %}
                    {% if j.post.id == i.id %}
                    <div class='flex' style="width:100%; display:flex;">
                        <div class="flex-item" style="width: 10%;">
                        </div>
                        <div class='flex-item' style='margin-top:10px'>
                            <img src="{{picture}}" alt="gambar" align="center" width = "55px" height = "55px" style="border-radius:50%">
                        </div>
                        <div class='flex-item' style="width: 87%;padding-left:15px;margin-top:10px">
                                <b> {{ j.nama }}</b>
                                <p class = "flex-item-status" style="font-size: 15px;word-wrap:break-word;">
                                        {{ j.comment | linebreaksbr }}
                                </p>
                                <div id="created_date" style="font-size:80%; font-style:italic;margin-bottom:5px; color: white"> 
                                    {{ j.comments_created_date | date:"d M Y H:i:s" }}
                                </div>
                        </div>
                    </div>
                    <br>
                    {% endif %}
                {% endfor %}
            </div>
            {% endfor %}
            </div>
        </div>
    </section>
</div>
{% endblock %}

app_profile_page/templates/profile_page.html
{% extends "base.html" %}
{% block content %}

<style type="text/css">
	.expertise{
	  margin-bottom: 20px; 
	}

	.turun-1{
	  margin-top: 10px;
	}

	.turun-2{
	  margin-top: 10px;
	}

	@media only screen and (max-width: 768px){
	  .expertise{
	    transform: translateY(10px);
	  }
	}

	@media only screen and (max-width: 594px){
	  .turun-1{
	    transform: translateY(20px);
	  }

	  .turun-2{
	    transform: translateY(20px);
	  }
	}

	@media only screen and (max-width: 460px){
	  .expertise{
	    display: grid;
	    width: 100px;
	}
}

@media only screen and (max-width: 375px){
	.turun-1{
    transform: translateY(40px);
	}

	.turun-2{
    transform: translateY(40px);
  	}
 }
</style>
<div class="container">
	<h3 padding: "10px">Profile</h3>                
	<div style="text-align:center;">
		<img src= "https://orig00.deviantart.net/08ce/f/2008/235/9/2/hepzibah_smith_by_jlestrange.jpg" width="200" height="200" style="border-radius: 50%"/>
	</div>
	<div style="text-align:center;">
		<h1 style="font-size: 250%"><b>{{name}}</b></h1>
	</div>
	<div class="flex" style="flex-direction:row;display: flex; width:100%; margin-top: 30px; align-self: center;">
		<div class = "col-xs-3">
		</div>
		<div class="flex-item" style="font-weight: bolder;">
			<p>Birthday</p>
			<p>Gender</p>
			<p>Description</p>
			<p class="turun-1">Email</p>
			<p class="turun-2">Expertise</p>
		</div>
		<div class="flex-item" style="margin-left:20px; width:70%">
			<p>: {{birth}}</p>
			<p>: {{gender}}</p>
			<p>: {{description}}</p>
			<p>: {{email}}</p>
			<div class="expertise">
				{% for ii in expertise %}
					<div class="col-md-2" style= "display: inline; padding: 5px; background: #0e76a8; border-radius: 8px; margin-right: 5px;margin-bottom: 10px; color: #ffffff; text-align: center;" ><b> {{ii}} </b></div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

app_statistic_page/templates/statistic_page.html
{% extends "base.html" %}
{% block content %}

<div class="container">
	<h3>Statistic</h3>
	<br>
	<section class="user-id">
		<div class="container">
			<div class="flex-id">
				<div>
					<img class="user-photo" src="https://orig00.deviantart.net/08ce/f/2008/235/9/2/hepzibah_smith_by_jlestrange.jpg" alt="gambar" width="100px" height="100px">
				</div>
				<div>
					<p class="user-name"><b>Hepzibah Smith</b></p>
				</div>
			</div>
		</div>
	</section>

	<section class="user-statistic">
		<div class="container">
			<div class="flex-stats">
                <div class="user-friend">
                    <div class="friend-icon">
                        <img src="https://i.imgur.com/B05ARxs.png" width="50px" height="50px" title="Friend">
                    </div>
                    <div class="number-of-friend" style="margin-left: 10px; transform: translateY(20px);">
                        {{number_of_friend}} People
                    </div>
                </div>
                <div class="user-feeds">
                	<div class="feed-icon">
                        <img src="https://i.imgur.com/6kUH4ZX.png" width="30px" height="30px" title="Feeds" style="transform: translateY(13px);">
                    </div>
                    <div class="number-of-feed" style="margin-left: 20px; transform: translateY(20px);">
                        {{number_of_feed}} Posts
                    </div>
                </div>
			</div>
		</div>
	</section>
	<section class="user-latest-post">
		<div id="container">
			<div style="margin-left: 55px; margin-top: 30px;">
				<p style="font-size: 20px;"><b>Latest Post:</b></p>
				<div class="flex-status" style="margin-left: 0px; margin-bottom: 10px; margin-top: 20px;">
                    <div class="friend-icon">
                        <img src="https://orig00.deviantart.net/08ce/f/2008/235/9/2/hepzibah_smith_by_jlestrange.jpg" width="50px" height="50px" title="Profile" style="border-radius:50%">
                    </div>
                    <div class="number-of-friend" style="margin-left: 10px; transform: translateY(20px);">
                        <b>Hepzibah Smith</b>
                    </div>
                </div>
				
				<div class="latest-post" style="left: -30px; top: 15px;">
		    		<p style="word-wrap:break-word; width: 90%;">{{ statusAkhir.status | linebreaksbr }}</p> 
		    		<p style="font-size:80%; font-style:italic;margin-bottom:5px; color: black;">{{statusAkhir.created_date | date:"d M Y H:i:s"}}</p>
				</div>
			</div>
		</div> 
	</section>
</div>

{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<!-- Block Base -->
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Tugas-1-PPW">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link rel="shortcut icon" href="https://img00.deviantart.net/29ca/i/2012/342/2/5/panda_vector__by_m_awesome-d5nggwg.png">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="{% static 'css/tugas1.css' %}" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet'> 
    <link href='https://fonts.googleapis.com/css?family=Titillium Web' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Josefin Sans' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Lobster' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Dancing Script' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Maven Pro' rel='stylesheet'>
	<title>Panda Rangers Social Media</title>
</head>

<body>
	<header>
        {% include "partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
        $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

templates/partials/footer.html
<div class="footer">
	<p><br>&copy; 2017 Coded with love by Us. All rights reserved</p>
</div>

templates/partials/header.html
<nav id="header" class="navbar navbar-fixed-top">
    <div id="header-container" class="container">
        <div class="navbar-header">
            <a id="brand" class="navbar-brand" href="/home-status">Panda Rangers</a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse justify-content-end">
        <ul class="nav navbar-nav navbar-right" id="nav">
          <li><a href="{% url 'home-status:index' %}">Status</a></li>
          <li><a href="{% url 'profile-page:index' %}">Profile</a> </li>
          <li><a href="{% url 'add-friend:index' %}">Friends</a></li>
          <li><a href="{% url 'my-stats:index' %}">Stats</a> </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div><!-- /.container -->
</nav><!-- /.navbar -->